<a href="https://colab.research.google.com/github/19PA1A04A4/python-basics/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a.shape)
a.ndim
a.dtype
a.itemsize
a.size
type(a)
np.zeros((2,4))
np.ones((3,4))
np.empty((2,3))
np.eye(4)
np.full((2,3),7)
np.random.random((2,3))
a=np.array([20,30,40,50])
b=np.array(4)
print(a)
print(b)
c=a-b
print(c)
print(b**c)
print(10*np.sin(a))
print(a<35)
a[0]+=10
print(a)
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])  
print(A)
print(B)
print(A * B)
print(A @ B)
print(A.dot(B))
print(np.dot(A,B))



(3, 5)
[20 30 40 50]
4
[16 26 36 46]
[      4294967296 4503599627370496                0                0]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[30 30 40 50]
[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [38]:
import numpy as np
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [43]:
import numpy as np
a=np.arange(5)
print(a)
b=np.random.random(5)
print(b)
print(np.add(a,b))
print(a+b)
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))

[0 1 2 3 4]
[0.28540482 0.1456533  0.11745381 0.07301249 0.03158577]
[0.28540482 1.1456533  2.11745381 3.07301249 4.03158577]
[0.28540482 1.1456533  2.11745381 3.07301249 4.03158577]
[-0.28540482  0.8543467   1.88254619  2.92698751  3.96841423]
[-0.28540482  0.8543467   1.88254619  2.92698751  3.96841423]
[0.         0.1456533  0.23490762 0.21903747 0.12634307]
[0.         0.1456533  0.23490762 0.21903747 0.12634307]
[  0.           6.86561861  17.02797045  41.08886121 126.63931842]
[  0.           6.86561861  17.02797045  41.08886121 126.63931842]


In [44]:
import numpy as np
a=np.arange(10)**3
print(a)
print(a[2])
print(a[2:4])
print(a[2:3])


[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27]
[8]


In [47]:
import numpy as np
a=np.arange(12).reshape(4,3)**2
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[2,])
print(a[:2],)
print(a[:3,])
print(a[:2,:3])
print(a[:,2])
print(a[2,:])

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[36 49 64]
[[ 0  1  4]
 [ 9 16 25]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 0  1  4]
 [ 9 16 25]]
[  4  25  64 121]
[36 49 64]


In [52]:
import numpy as np
a=np.floor(10*np.random.random((3,4)))
print(a)

[[0. 2. 6. 5.]
 [4. 8. 1. 0.]
 [7. 8. 5. 0.]]
